name: 'Issue Linker Branch Check'

description: 'Check if branch name contains an existing GitHub issue number'

author: 'Suguru Takahashi'

branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  branch:
    description: |
      Branch name to check
      Default: current branch
    required: false
  repo:
    description: |
      Repository in owner/repo format
      Default: current repository
    required: false
  exclude-pattern:
    description: |
      Glob pattern to exclude branches from validation
      Default: '{main,master,develop}'
      Pattern examples:
        '{main,master,develop}'  - exclude specific branches
        'release/*'              - exclude with wildcard
        '{release,hotfix}/*'     - exclude multiple prefixes
        '!(feature|bugfix)/*'    - exclude all except these
    required: false
    default: '{main,master,develop}'
  issue-status:
    description: |
      Filter by issue status
      Options: 'all', 'open', 'closed'
      Default: 'all' (checks both open and closed issues)
    required: false
    default: 'all'
  github-token:
    description: |
      GitHub token for API access
      Default: uses GITHUB_TOKEN from environment
    required: false
    default: ${{ github.token }}

outputs:
  status:
    description: 'Status of the check (ok or failed)'

runs:
  using: 'node20'
  main: 'packages/action/dist/index.js'
