name: 'Issue Linker'

description: 'Validate text contains valid GitHub issue numbers'

author: 'Suguru Takahashi'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  # Simple mode (automatic validations)
  validate-branch:
    description: 'Validate branch name'
    required: false
    default: 'false'
  validate-pr-title:
    description: 'Validate PR title'
    required: false
    default: 'false'
  validate-pr-body:
    description: 'Validate PR body'
    required: false
    default: 'false'
  validate-commits:
    description: 'Validate all commit messages in the PR'
    required: false
    default: 'false'
  comment-on-issues-when-branch-pushed:
    description: |
      Comment on detected issues when a branch is first pushed to GitHub.
      Requires validate-branch to be enabled.
      Works best with the 'create' event trigger.
    required: false
    default: 'false'
  
  # Advanced mode (custom text)
  text:
    description: 'Custom text to validate'
    required: false
  check-mode:
    description: |
      Check mode for finding issue numbers
      Options: 'default', 'branch', 'commit'
    required: false
    default: 'default'
  exclude:
    description: 'Custom exclude pattern (overrides check mode defaults)'
    required: false
  
  # Common settings
  issue-status:
    description: |
      Issue status filter
      Options: 'all', 'open', 'closed'
    required: false
    default: 'all'
  repo:
    description: |
      Repository in owner/repo format
      Default: current repository
    required: false
    default: ${{ github.repository }}
  github-token:
    description: |
      GitHub token for API access
      Default: uses GITHUB_TOKEN from environment
    required: false
    default: ${{ github.token }}
  hostname:
    description: |
      GitHub hostname for Enterprise Server
      Default: automatically detected from environment
    required: false

outputs:
  success:
    description: 'Whether all validations passed'
  results:
    description: 'All validation results as JSON'
  summary:
    description: 'Summary of validations (JSON)'

runs:
  using: 'node20'
  main: 'packages/action/dist/index.js'
