name: 'Issue Linker'

description: 'Validate text contains valid GitHub issue numbers'

author: 'Suguru Takahashi'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  # Simple mode (automatic validations)
  validate-branch:
    description: 'Validate branch name'
    required: false
    default: 'false'
  validate-pr-title:
    description: 'Validate PR title'
    required: false
    default: 'false'
  validate-pr-body:
    description: 'Validate PR body'
    required: false
    default: 'false'
  validate-commits:
    description: 'Validate all commit messages in the PR'
    required: false
    default: 'false'
  
  # Advanced mode (custom text)
  text:
    description: 'Custom text to validate'
    required: false
  mode:
    description: |
      Extraction mode
      Options: 'default', 'branch', 'commit'
    required: false
    default: 'default'
  exclude:
    description: 'Custom exclude pattern (overrides mode defaults)'
    required: false
  
  # Common settings
  issue-status:
    description: |
      Issue status filter
      Options: 'all', 'open', 'closed'
    required: false
    default: 'all'
  repo:
    description: |
      Repository in owner/repo format
      Default: current repository
    required: false
    default: ${{ github.repository }}
  github-token:
    description: |
      GitHub token for API access
      Default: uses GITHUB_TOKEN from environment
    required: false
    default: ${{ github.token }}

outputs:
  success:
    description: 'Whether all validations passed'
  failed-validations:
    description: 'List of failed validations (JSON)'
  found-issues:
    description: 'List of found issue numbers (JSON)'

runs:
  using: 'node20'
  main: 'packages/action/dist/index.js'
