name: ci-pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

# Cancel old runs when new commits are pushed
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci-pull-request:
    # Skip draft PRs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          # Always recreate bun.lock to ensure consistency
          rm -f bun.lock
          bun install
          
          if [[ "${{ github.event.pull_request.user.login }}" == "github-actions[bot]" ]]; then
            # Release-please PR: Skip lockfile check
            echo "✅ Skipping lockfile check for release-please PR"
          else
            # Regular PR: Verify lockfile is in sync
            if ! git diff --exit-code bun.lock > /dev/null 2>&1; then
              echo "❌ bun.lock is out of sync! Please run: rm -f bun.lock && bun install"
              git diff bun.lock
              exit 1
            fi
          fi

      - name: Check code quality
        run: bun run check

      - name: Build
        run: bun run build

      - name: Type check
        run: bun run typecheck

      - name: Check dependencies
        run: bun run knip

      - name: Test
        run: bun run test

      - name: Test Coverage
        run: bun run test:coverage
        continue-on-error: true  # TODO: Remove once test output format bug is fixed

      - name: Generate TypeScript dependency graph
        uses: ysk8hori/delta-typescript-graph-action@v1.2.4
        env:
          HUSKY: 0
        with:
          tsconfig: './tsconfig.base.json' # Path to your TypeScript config file
          orientation: 'LR' # Change to 'TB' for top-bottom orientation
          max-size: 50 # default is 30, adjust as needed
          # NOTE: show-metrics is set to false because enabling it produced too much output for this repository.
          show-metrics: false # Set to true to include metrics in the graph (output was too large when enabled)
          comment-title: '📊 Dependency Graph Changes'
          include-index-file-dependencies: false # Set to true if you want to include index.ts dependencies

      - name: Upload coverage to Codecov
        if: github.actor != 'github-actions[bot]'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}     # Required for private repos
          files: ./coverage/lcov.info             # Path to coverage report
          verbose: true                           # Enable verbose logging for debugging
          fail_ci_if_error: false                 # Don't fail CI if upload fails
          flags: unittests                        # Tag coverage as unit tests
          disable_search: false                   # Enable automatic coverage file search
          report_type: coverage                   # Specify coverage report type

      - name: E2E Tests
        run: bun scripts/testing/e2e-simple.ts 
