name: ci-sync-bun-lock-from-release-pr

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [main]
    paths:
      - '.release-please-manifest.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-bun-lock:
    # Only run on release-please PRs
    if: |
      contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Regenerate bun.lock
        run: |
          rm -f bun.lock
          bun install
          
      - name: Commit and push if changed
        id: commit
        run: |
          if ! git diff --quiet -- bun.lock; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add bun.lock
            git commit -m "chore: sync bun.lock with version bump"
            git push
            echo "bun_lock_updated=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to bun.lock"
            echo "bun_lock_updated=false" >> $GITHUB_OUTPUT
          fi
      
      # Update release-please PR after bun.lock sync
      - name: Update Release PR
        if: steps.commit.outputs.bun_lock_updated == 'true'
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
